LEADER_ENABLE = no
RGB_MATRIX_CUSTOM_USER = yes
NKRO_ENABLE = yes
DYNAMIC_MACRO_ENABLE = no
# KEY_OVERRIDE_ENABLE = yes
VIA_ENABLE = yes

# Firmware size Optimizations
TAP_DANCE_ENABLE   = yes
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
UNICODEMAP_ENABLE  = no
SPLIT_KEYBOARD    = no
CONSOLE_ENABLE = no
KEY_LOCK_ENABLE = no
