LEADER_ENABLE = no
RGB_MATRIX_CUSTOM_USER = yes
NKRO_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
# KEY_OVERRIDE_ENABLE = yes

# Firmware size Optimizations
EXTRAFLAGS += -flto
TAP_DANCE_ENABLE   = no
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
UNICODEMAP_ENABLE  = no
SPLIT_KEYBOARD    = no
CONSOLE_ENABLE = no
LTO_ENABLE = yes
KEY_LOCK_ENABLE = no
